server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social_system?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: chronos
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "*"
      allowed-headers: "*"

jwt:
  secret: your_jwt_secret_key_here
  expiration: 86400000 # 24 hours 