server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3310/campus_platform?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: chronos
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  # 添加额外的数据源配置
  sql:
    init:
      mode: always
      continue-on-error: true
